app/controllers/shelters_controller.rb
app/views/shelters/show.html.erb
config/routes.rb
spec/features/shelters/index_spec.rb

User story 3

---

app/controllers/shelters_controller.rb
app/views/shelters/index.html.erb
app/views/shelters/new.html.erb
app/views/shelters/show.html.erb
config/routes.rb
spec/features/shelters/index_spec.rb

User story 4

---

app/controllers/shelters_controller.rb
app/views/shelters/edit.html.erb
app/views/shelters/show.html.erb
config/routes.rb
spec/features/shelters/index_spec.rb

User story 5

---

app/controllers/shelters_controller.rb
app/views/shelters/show.html.erb
config/routes.rb
spec/features/shelters/destroy_spec.rb
spec/features/shelters/edit_spec.rb
spec/features/shelters/new_spec.rb
spec/features/shelters/show_spec.rb

User story 6

---

app/controllers/pets_controller.rb
app/models/pet.rb
app/views/pets/index.html.erb
config/routes.rb
db/migrate/20200819204204_create_pets.rb
db/schema.rb
spec/features/pets/index_spec.rb

User story 7

---

README.md

Add user stories to readme

---

app/controllers/pets_controller.rb
app/views/pets/show.html.erb
config/routes.rb
db/migrate/20200820205249_add_description_to_pets.rb
db/migrate/20200821004732_add_status_to_pets.rb
db/schema.rb
spec/features/pets/index_spec.rb
spec/features/pets/show_spec.rb

User story 9

---

app/models/shelter.rb
app/models/shelter_review.rb
app/views/shelters/show.html.erb
db/migrate/20200825031745_create_shelter_reviews.rb
db/migrate/20200825032503_add_shelter_to_shelter_reviews.rb
db/schema.rb
spec/features/shelter_reviews/show_spec.rb
user_stories.md

User Story 2, Shelter Reviews
As a visitor,
When I visit a shelter's show page,
I see a list of reviews for that shelter
Each review will have:
- title
- rating
- content
- an optional picture

User story 2

---

app/assets/stylesheets/application.css
app/controllers/shelter_reviews_controller.rb
app/views/layouts/application.html.erb

Adds:
- Error messaging styling to css file
- If logic statement to shelter reviews controller for successful form submit
- Flash messaging to reviews html

User story 5 updates

---

app/controllers/favorites_controller.rb
app/views/favorites/index.html.erb
spec/features/favorites/index_spec.rb

User Story 14, No Favorites Page
As a visitor
When I have not added any pets to my favorites list
And I visit my favorites page ("/favorites")
I see text saying that I have no favorited pets

User story 14

---

app/controllers/adoption_applications_controller.rb
app/models/adoption_application.rb
app/poros/favorites.rb
app/views/adoption_applications/new.html.erb
app/views/favorites/index.html.erb
config/routes.rb
db/migrate/20200830001443_create_adoption_applications.rb
db/schema.rb
spec/features/adoption_applications/new_spec.rb

User Story 16, Applying for a Pet
As a visitor
When I have added pets to my favorites list
And I visit my favorites page ("/favorites")
I see a link for adopting my favorited pets
When I click that link I'm taken to a new application form
At the top of the form, I can select from the pets of which I've favorited for which I'd like this application to apply towards (can be more than one)
When I select one or more pets, and fill in my
- Name
- Address
- City
- State
- Zip
- Phone Number
- Description of why I'd make a good home for this/these pet(s)
And I click on a button to submit my application
I see a flash message indicating my application went through for the pets that were selected
And I'm taken back to my favorites page where I no longer see the pets for which I just applied listed …

User story 16

---

spec/features/adoption_applications/new_spec.rb
user_stories.md

User Story 17, Incomplete application for a Pet
As a visitor
When I apply for a pet and fail to fill out any of the following:
- Name
- Address
- City
- State
- Zip
- Phone Number
- Description of why I'd make a good home for this/these pet(s)
And I click on a button to submit my application
I'm redirect back to the new application form to complete the necessary fields
And I see a flash message indicating that I must complete the form in order to submit the application

User story 17

---

app/views/pets/show.html.erb
spec/features/adoption_applications/show_spec.rb
spec/features/pet_adoptions/index_spec.rb
user_stories.md

[x] done
User Story 20, Pet Applications Index Page
As a visitor
When I visit a pets show page
I see a link to view all applications for this pet
When I click that link
I can see a list of all the names of applicants for this pet
Each applicant's name is a link to their application show page

User story 20

---

app/controllers/pet_adoptions_controller.rb
app/views/pet_adoptions/index.html.erb
app/views/pets/show.html.erb
config/routes.rb
spec/features/pet_adoptions/index_spec.rb
user_stories.md

You were right, we did need to have an index page for the applications.  I added it, but needed another route, I can explain tomorrow.  We are good through US#21.
User Story 20, Pet Applications Index Page
As a visitor
When I visit a pets show page
I see a link to view all applications for this pet
When I click that link
I can see a list of all the names of applicants for this pet
Each applicant's name is a link to their application show page
[x] done
User Story 21, Pet Applications Index Page When No Applications
As a visitor
When I visit a pet applications index page for a pet that has no applications on them
I see a message saying that there are no applications for this pet yet

User story 21

---

app/controllers/shelters_controller.rb
spec/features/favorites/delete_spec.rb
spec/features/shelters/destroy_spec.rb
spec/features/shelters/new_spec.rb
user_stories.md

[x] done
User Story 29, Flash Messages for Shelter Create and Update
As a visitor
When I am updating or creating a new shelter
If I try to submit the form with incomplete information
I see a flash message indicating which field(s) I am missing

User story 29

---

app/controllers/shelters_controller.rb
app/models/shelter.rb
app/models/shelter_review.rb
app/views/shelters/show.html.erb
spec/features/adoption_applications/new_spec.rb
spec/features/shelter_reviews/new_spec.rb
spec/features/shelters/new_spec.rb
spec/features/shelters/show_spec.rb
user_stories.md

User Story 30, Shelter Statistics
As a visitor
When I visit a shelter's show page
I see statistics for that shelter, including:
- count of pets that are at that shelter
- average shelter review rating
- number of applications on file for that shelter

User story 30

---

spec/features/pet_adoptions/index_spec.rb
spec/features/shelters/new_spec.rb
spec/models/adoption_application_spec.rb
spec/models/application_record_spec.rb
spec/models/pet_adoption_spec.rb
spec/models/shelter_review_spec.rb

Adds missing model tests to spec to get to 100%

Adds missing model tests to spec

---

app/views/pet_adoptions/index.html.erb

Adds link to Pet name in pet adoptions show page

Updates adoption view to include link for pet name

---

app/views/pets/show.html.erb
spec/features/pets/show_spec.rb

User Story 36, All Applicant Names are links to that Applicant's application
As a visitor
Any time I see an applicant's name within this application
It is a link to their application show page
User Story 35, All Shelter Names are links to that Shelter's Show Page
As a visitor
Any time I see a shelter's name within this application
It is a link to their show page

Updates pets show page to link adopter, and includes test

---

app/controllers/favorites_controller.rb
app/controllers/pet_adoptions_controller.rb
app/controllers/pets_controller.rb
spec/features/favorites/update_spec.rb
spec/features/pets/destroy_spec.rb
spec/features/shelter_reviews/update_spec.rb

Address gaps in test coverage
